### ISSUE TITLE
Don't use env variables for passing variables to bash script

### ISSUE THREAD

**Issue by jelmervdl** [jelmervdl/empty-train#21]
The commands in the filter json files are just lines of bash shell script. Right now we pass the variables from the interface to this script by defining them as environment variables when the line of shell script is executed. But they are also inherited by all the subprocesses at that point.

Now say you define a placeholder/variable `LANG` in your filter script. And that script will call some perl script to do the actual filtering. Now Perl will complain that the LANG environment variable is not set to a valid language.

Ideally we can somehow pass variables to the bash script in a way that it is still Bash that does the variable expansion (because Bash has quite a few nifty features when doing that) but not cause the variables to be inherited by the subprocesses.

**Comment by ales-t** [comment]
@jelmervdl would it make sense to be quite pragmatic and simply prefix all variables with some "unique" name, such as `__EMPTY_TRAIN_VAR_`? So `LANG` would become `__EMPTY_TRAIN_VAR_LANG`, for instance. That way, my guess is we could keep almost all of the current implementation and avoid clashes.

**Comment by jelmervdl** [comment]
Would work, but wouldn't look very nice. Maybe we could automate adding the prefix, i.e. do it when creating the env variables dict. But then that would also entail doing a search/replace on the command string, which might be complex for cases such as `${LANG2:+--trg-lang $LANG2}` and `${DEBUG:+--debug}`. But probably do-able? Hmm, Python doesn't seem to have recursive regexp out of the box…

It might be easier to edit the command on the fly? E.g. do something like:
```py
from shlex import quote
command = ';'.join([f'{key}={quote(value)}' for key, value in parameters.items()] + [command])
```
That would produce something like `LANG=eng; THRESHOLD=0.2; ./filter.sh $LANG $THRESHOLD` which seems to do what you'd expect: variable substitution works, but ./filter.sh won't see LANG or THRESHOLD in its environment.

I haven't tested if `quote()` is enough to make this safe, and maybe there needs to be some validation on `key` if we'd do this.

**Comment by ales-t** [comment]
You can check the PR https://github.com/jelmervdl/empty-train/pull/27

It's still in draft, I haven't tested it much but it seems to work for the basic cases.
