### ISSUE TITLE
Corpus display broken on Chromium/Linux

### ISSUE THREAD

**Issue by XapaJIaMnu** [jelmervdl/empty-train#7]
Chromium/Linux doesn't display the corpus:
![Screenshot_20220713_121423](https://user-images.githubusercontent.com/2027221/178721125-d96f13e9-b615-4cd1-98f4-c5db8c83cb9a.png)

Firefox on the other hand works:
![Screenshot_20220713_121501](https://user-images.githubusercontent.com/2027221/178721157-130304db-8598-4aed-bc39-1e88418351d2.png)

**Comment by jelmervdl** [comment]
Fixed in 081638d838c281887294d50d0a56e1fb6240dbbf and 0c4fbb36dfa9c98f6c2d811d45f3b126f4d921aa.
